load-image
andrii-telishko/event-boostert-team-project pull request #1
Opened 2021-05-08 10:06 UTC by 2F4S7

Загрузил картинки.

2021-05-08 17:30 UTC, andrii-telishko requested changes
Привіт. Нам картинки event не потрібні. Ми ж будемо їх рендерити з серверу.  Ще я думаю, що краще скачати все лого і потім його абсолютом поставити в куток героя. Тому кожну літеру, думаю не потрібно скачувати. І ще там на фоні карточок з івентами є мало помітна svg. Її також треба скачати для десктопа, таблетки та мобілки. Так ніби все. Ще можна картинки в одній папці тримати, а svg в іншій.

2021-05-08 18:57 UTC, 2F4S7 commented
Сделал update файлов и добавил что просили

2021-05-08 19:41 UTC, andrii-telishko requested changes
Додай ще будь-ласка для героя png 1x 2x 3x, для мобілки, таблетки та десктора. В тебе деякі є, але не всі!

2021-05-08 20:27 UTC, 2F4S7 commented
> Додай ще-ласка для героя png 1x 2x 3x, для мобильных устройств, таблетки та десктора. В тебе деякі є, але не все!
Зробив!

2021-05-08 20:28 UTC, 2F4S7 commented
Зробив!

2021-05-09 08:45 UTC, andrii-telishko approved these changes
все ок

2021-05-09 08:45 UTC, merged